import { BookingOption, BookingSummary, Conversation, LookupValue, StudentDashboard, TutorDashboard, TutorProfile, TutorSummary } from '../models/api.models';

const img = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=400&q=80`;

export const mockTutors: TutorSummary[] = [
  {
    id: 'ayesha-malik',
    name: 'Ayesha Malik',
    photoUrl: img('1573496359142-b8d87734a5a2'),
    initials: 'AM',
    verified: true,
    rating: 4.9,
    reviews: 184,
    city: 'Lahore',
    subjects: ['Mathematics', 'Physics'],
    classLevels: ['O Levels', 'A Levels'],
    experienceYears: 8,
    feeText: 'PKR 18,000/month',
    feeAmount: 18000,
    teachingMode: 'Both',
    languages: ['English', 'Urdu'],
    nextSlot: 'Today, 6:00 PM',
    gender: 'Female',
    responseTime: 'Replies in 12 min',
    studentsTaught: 240,
    matchPercentage: 98,
    matchReason: 'Perfect fit for A Levels Math & Physics in Lahore',
    tagline: 'Cambridge A* in Math. I make hard problems feel obvious.',
  },
  {
    id: 'hamza-raza',
    name: 'Hamza Raza',
    photoUrl: img('1507003211169-0a1dd7228f2d'),
    initials: 'HR',
    verified: true,
    rating: 4.8,
    reviews: 126,
    city: 'Karachi',
    subjects: ['Chemistry', 'Biology'],
    classLevels: ['MDCAT', 'A Levels'],
    experienceYears: 6,
    feeText: 'PKR 2,500/hour',
    feeAmount: 20000,
    teachingMode: 'Online',
    languages: ['English', 'Urdu'],
    nextSlot: 'Tomorrow, 4:30 PM',
    gender: 'Male',
    responseTime: 'Replies in 20 min',
    studentsTaught: 180,
    matchPercentage: 95,
    matchReason: 'MDCAT specialist, 92% admit rate',
    tagline: 'MDCAT Chemistry - frameworks not memorization.',
  },
  {
    id: 'fatima-shah',
    name: 'Fatima Shah',
    photoUrl: img('1580489944761-15a19d654956'),
    initials: 'FS',
    verified: true,
    rating: 5,
    reviews: 92,
    city: 'Islamabad',
    subjects: ['English', 'IELTS'],
    classLevels: ['O Levels', 'IELTS'],
    experienceYears: 5,
    feeText: 'PKR 12,000/month',
    feeAmount: 12000,
    teachingMode: 'Both',
    languages: ['English', 'Urdu'],
    nextSlot: 'Today, 8:00 PM',
    gender: 'Female',
    responseTime: 'Replies in 8 min',
    studentsTaught: 140,
    matchPercentage: 93,
    matchReason: 'IELTS 8.5 - band 7+ guarantee',
    tagline: 'IELTS Band 8.5. I get you to 7+ in 6 weeks.',
  },
  {
    id: 'umar-khan',
    name: 'Umar Khan',
    photoUrl: img('1519085360753-af0119f7cbe7'),
    initials: 'UK',
    verified: true,
    rating: 4.7,
    reviews: 78,
    city: 'Lahore',
    subjects: ['Computer Science', 'Mathematics'],
    classLevels: ['A Levels', 'University'],
    experienceYears: 4,
    feeText: 'PKR 2,500/hour',
    feeAmount: 22000,
    teachingMode: 'Online',
    languages: ['English', 'Urdu'],
    nextSlot: 'Tomorrow, 7:00 PM',
    gender: 'Male',
    responseTime: 'Replies in 15 min',
    studentsTaught: 95,
    tagline: 'Ex-FAST. Code, calculus, and confidence.',
  },
  {
    id: 'sana-iqbal',
    name: 'Sana Iqbal',
    photoUrl: img('1438761681033-6461ffad8d80'),
    initials: 'SI',
    verified: true,
    rating: 4.9,
    reviews: 210,
    city: 'Karachi',
    subjects: ['Quran', 'Islamiat'],
    classLevels: ['School', 'Adult'],
    experienceYears: 10,
    feeText: 'PKR 8,000/month',
    feeAmount: 8000,
    teachingMode: 'Both',
    languages: ['Urdu', 'Arabic', 'English'],
    nextSlot: 'Today, 5:00 PM',
    gender: 'Female',
    responseTime: 'Replies in 5 min',
    studentsTaught: 320,
    tagline: 'Tajweed, tarjuma, and tafseer with love.',
  },
  {
    id: 'bilal-ahmed',
    name: 'Bilal Ahmed',
    photoUrl: img('1492562080023-ab3db95bfbce'),
    initials: 'BA',
    verified: true,
    rating: 4.8,
    reviews: 64,
    city: 'Islamabad',
    subjects: ['Physics', 'Mathematics'],
    classLevels: ['ECAT', 'A Levels'],
    experienceYears: 7,
    feeText: 'PKR 18,000/month',
    feeAmount: 18000,
    teachingMode: 'Home',
    languages: ['English', 'Urdu'],
    nextSlot: 'Wed, 6:30 PM',
    gender: 'Male',
    responseTime: 'Replies in 25 min',
    studentsTaught: 130,
    tagline: 'NUST gold medalist. Physics is a story, let me tell it.',
  },
];

export const mockLookups: Record<string, LookupValue[]> = {
  city: ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan', 'Peshawar', 'Hyderabad', 'Quetta', 'Sialkot'].map((name, index) => value('city', name, index)),
  subject: ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'English', 'Computer Science', 'O Levels', 'A Levels', 'IELTS', 'Quran', 'SAT', 'MDCAT', 'ECAT', 'University Courses'].map((name, index) => value('subject', name, index)),
  class_level: ['Grade 1-5', 'Grade 6-8', 'Grade 9-10 / O Levels', 'A Levels', 'University', 'Test Prep'].map((name, index) => value('class_level', name, index)),
  teaching_mode: ['Online', 'Home', 'Both'].map((name, index) => value('teaching_mode', name, index)),
  gender: ['Any', 'Female', 'Male'].map((name, index) => value('gender', name, index)),
  language: ['English', 'Urdu', 'Arabic'].map((name, index) => value('language', name, index)),
};

export const mockStudentDashboard: StudentDashboard = {
  welcomeName: 'Zara',
  headline: 'As-salamu alaykum, Zara',
  subheadline: 'You have 1 demo class today and 3 new tutor matches.',
  stats: [
    { label: 'Active sessions', value: '3', caption: '1 this week', icon: 'book', tone: 'success' },
    { label: 'Upcoming demos', value: '2', caption: 'Today, 6 PM', icon: 'calendar', tone: 'success' },
    { label: 'Saved tutors', value: '8', caption: '2 new', icon: 'heart', tone: 'success' },
    { label: 'Avg progress', value: '+18%', caption: 'Last 30 days', icon: 'trending-up', tone: 'success' },
  ],
  recommendedTutors: mockTutors.slice(0, 2),
  progress: [
    { label: 'Mathematics', percentage: 78 },
    { label: 'Physics', percentage: 62 },
    { label: 'English', percentage: 91 },
  ],
  upcomingDemos: [
    { tutorName: 'Ayesha Malik', tutorPhotoUrl: mockTutors[0].photoUrl, subject: 'Mathematics', startsAt: 'Today, 6:00 PM', actionLabel: 'Join' },
    { tutorName: 'Fatima Shah', tutorPhotoUrl: mockTutors[2].photoUrl, subject: 'English', startsAt: 'Tomorrow, 8:00 PM', actionLabel: 'Join' },
  ],
  messages: mockTutors.slice(0, 3).map((tutor, index) => ({ personName: tutor.name, photoUrl: tutor.photoUrl, preview: "Looking forward to today's class!", time: `5:4${index}p` })),
  recentActivity: [
    { text: 'Booked demo with Ayesha M.', timeAgo: '1h ago', tone: 'cyan' },
    { text: 'Saved Hamza R. to favorites', timeAgo: '2h ago', tone: 'violet' },
    { text: 'Completed Physics session with Bilal A.', timeAgo: '3h ago', tone: 'success' },
    { text: 'AI matched 3 new tutors', timeAgo: '4h ago', tone: 'cyan' },
  ],
};

export const mockTutorDashboard: TutorDashboard = {
  tutorName: 'Ayesha',
  headline: 'Good evening, Ayesha',
  subheadline: '4 new student requests and 2 demo classes this week.',
  profileStrength: 92,
  stats: [
    { label: 'Monthly earnings', value: 'PKR 184,000', caption: '22% vs last month', icon: 'wallet', tone: 'success' },
    { label: 'Active students', value: '12', caption: '3 this month', icon: 'users', tone: 'success' },
    { label: 'Demo bookings', value: '8', caption: 'this week', icon: 'calendar', tone: 'cyan' },
    { label: 'Avg rating', value: '4.9', caption: '184 reviews', icon: 'star', tone: 'warning' },
  ],
  earnings: { labels: ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], values: [120, 150, 168, 172, 181, 184], totalText: 'PKR 1,128,000' },
  studentRequests: [
    { initial: 'H', studentName: 'Hassan A.', detail: 'A Levels Physics - Lahore', receivedAt: '2 hrs ago' },
    { initial: 'M', studentName: 'Maria K.', detail: 'O Levels Math - Online', receivedAt: 'Yesterday' },
    { initial: 'B', studentName: 'Bilal N.', detail: 'A Levels Math - Lahore', receivedAt: 'Yesterday' },
    { initial: 'S', studentName: 'Sara F.', detail: 'MDCAT Chemistry - Online', receivedAt: '2 days ago' },
  ],
  subjectPerformance: [
    { subject: 'Mathematics', rating: 4.95, retentionPercentage: 98 },
    { subject: 'Physics', rating: 4.85, retentionPercentage: 94 },
  ],
  availability: ['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((day, index) => ({ day, slots: [index % 3 === 0, index % 3 === 2, index % 3 === 1, index % 3 === 0] })),
  recentReviews: [
    { reviewerName: 'Amna K.', context: 'Parent', rating: 5, quote: "Best math teacher we've ever hired.", createdAt: new Date().toISOString() },
    { reviewerName: 'Hassan R.', context: 'Student', rating: 5, quote: 'Got A* - would not have without her.', createdAt: new Date().toISOString() },
  ],
  responseRate: { percentage: 96, averageReply: 'Avg reply: 12 min', rank: 'Top 5% tutors', delta: '+4% this month' },
};

export const mockConversations: Conversation[] = mockTutors.map((tutor, index) => ({
  id: tutor.id,
  personName: tutor.name,
  photoUrl: tutor.photoUrl,
  verified: tutor.verified,
  status: 'Online - usually replies in 12 min',
  lastMessage: 'See you at the demo!',
  lastMessageTime: `5:4${index}p`,
  messages: index === 0 ? [
    { id: '1', sender: 'tutor', body: 'Walaikum salam Zara! Looking forward to our demo today.', time: '5:42 PM', isMine: false },
    { id: '2', sender: 'me', body: "Sir actually I'm a bit anxious about projectile motion. Can we focus there?", time: '5:44 PM', isMine: true },
    { id: '3', sender: 'tutor', body: "Absolutely. I'll bring 3 worked examples. We'll have it cracked in 20 min.", time: '5:45 PM', isMine: false },
    { id: '4', sender: 'tutor', body: "Also - can you share the past paper you tried? I'd like to see where you got stuck.", time: '5:45 PM', isMine: false },
    { id: '5', sender: 'me', body: 'Sending now', time: '5:48 PM', isMine: true },
  ] : [],
}));

export function profileFor(id: string): TutorProfile {
  const summary = mockTutors.find(tutor => tutor.id === id) ?? mockTutors[0];
  return {
    summary,
    about: 'LUMS graduate with years of tutoring O/A Levels. Specializing in turning anxiety into grades through structured frameworks.',
    teachingStyle: 'Quick diagnosis, worked examples, guided practice, and a clear recap after each class.',
    education: ['BSc Mathematics, LUMS', 'Cambridge CIE Certified'],
    achievements: ['95% of students improved by 2+ grades', 'Top 1% on Lumora 2024'],
    availability: ['Mon 6 PM', 'Wed 6 PM', 'Sat 3 PM'],
    reviews: [
      { reviewerName: 'Amna K.', context: 'Parent', rating: 5, quote: "Best math teacher we've ever hired.", createdAt: new Date().toISOString() },
      { reviewerName: 'Hassan R.', context: 'A Level Student', rating: 5, quote: 'The demo class let me test the tutor before paying.', createdAt: new Date().toISOString() },
    ],
  };
}

export function bookingFor(id: string): BookingOption {
  const tutor = mockTutors.find(item => item.id === id) ?? mockTutors[0];
  return {
    tutorId: tutor.id,
    tutorName: tutor.name,
    tutorPhotoUrl: tutor.photoUrl,
    subjects: tutor.subjects,
    dates: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'].map((label, index) => ({ label, day: 18 + index, isoDate: `2026-05-${18 + index}` })),
    timeSlots: ['4:00 PM', '5:00 PM', '6:00 PM', '7:00 PM', '8:00 PM'],
    modes: ['Online', 'Home tuition'],
    safetyNotes: ['Verified tutor with CNIC check', 'Recorded for safety (online)', 'No payment until you commit'],
  };
}

export const mockBookings: BookingSummary[] = [
  {
    id: 'demo-ayesha',
    tutorId: 'ayesha-malik',
    tutorName: 'Ayesha Malik',
    tutorPhotoUrl: mockTutors[0].photoUrl,
    subjects: ['Mathematics', 'Physics'],
    bookingDate: '2026-05-18',
    bookingTime: '6:00 PM',
    teachingMode: 'Online',
    status: 'confirmed',
    learningGoal: 'Focus on A Levels mechanics and exam timing.',
    createdAtUtc: new Date().toISOString(),
  },
  {
    id: 'demo-fatima',
    tutorId: 'fatima-shah',
    tutorName: 'Fatima Shah',
    tutorPhotoUrl: mockTutors[2].photoUrl,
    subjects: ['English', 'IELTS'],
    bookingDate: '2026-05-19',
    bookingTime: '8:00 PM',
    teachingMode: 'Online',
    status: 'pending',
    learningGoal: 'IELTS writing band improvement.',
    createdAtUtc: new Date().toISOString(),
  },
];

function value(groupCode: string, name: string, index: number): LookupValue {
  return { id: index + 1, groupCode, code: name.toLowerCase().replaceAll(' ', '-'), name, sortOrder: index + 1, isActive: true };
}
